### PR TITLE
Onboarding: Ask and show gender to users

### LINKED ISSUE #4: Onboarding
ask for more info while onboarding:
1. Gender
2. Interests (optional)
3. others

### PR DESCRIPTION
**Pull request by HarshNarayanJha**
This PR adds a select to ask the user for their gender and extends socket events to send and receive gender information, which is shown on the chat page besides the partner's name.

I will also open a supporting PR on the backend's repo

Closes #4

### CODE REVIEW

**Comment by Suyious** [comment]
@HarshNarayanJha You are requested to please refrain from pushing to master. Your efforts are appreciated. I have looked at your changes and we might integrate it once the actual gender filter functionality has been established. 

Note: Please look into why we are not supposed to push to master in case you are a beginner. Short story: If the master in the original doesn't match the master in your fork, we might have serious conflicts. Hope that's clear.

**Comment by HarshNarayanJha** [comment]
Thanks!
Right, sorry about that, I was about to make a new branch but forgot before opening the PR 😢. I will take care of that issue the next time.

Though, are you referring to my master branch or upstream's master branch?

**Comment by Suyious** [comment]
The pull request should look something like this:
Suyious:master from HarshNarayanJha:feature-branch

I hope this makes it clear for you. I was referring to not create a pull request from the master in your fork.

**Comment by HarshNarayanJha** [comment]
Closing

**Pull request closed without merging**
